version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/snail
hooks:
  ApplicationStart:
    - location: scripts/run-server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: root
